### ISSUE TITLE
( BUG )  Can't access settings or get out of Developer after Accounting module install

### ISSUE THREAD

**Issue by Circlegent** [odoomates/odooapps#122]
Hello,
After install of accounting module I am unable to access settings or get out of developer mode at all.  This is a major issue that I am hoping can be resolved right away as I am days away from presenting this to company higher ups.

Latest 17.0 build

UncaughtPromiseError > OwlError
Uncaught Promise > An error occured in the owl lifecycle (see this Error's "cause" property)
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (http://localhost:8069/web/assets/b1c24d7/web.assets_web.min.js:916:101)
    at App.handleError (http://localhost:8069/web/assets/b1c24d7/web.assets_web.min.js:1542:29)
    at ComponentNode.initiateRender (http://localhost:8069/web/assets/b1c24d7/web.assets_web.min.js:1006:19)

Caused by: Error: "res.config.settings"."anglo_saxon_accounting" field is undefined.
    at Field.parseFieldNode (http://localhost:8069/web/assets/b1c24d7/web.assets_web.min.js:7657:231)
    at http://localhost:8069/web/assets/b1c24d7/web.assets_web.min.js:8534:865
    at visit (http://localhost:8069/web/assets/b1c24d7/web.assets_web.min.js:4221:51)
    at visitChildren (http://localhost:8069/web/assets/b1c24d7/web.assets_web.min.js:4220:171)
    at visit (http://localhost:8069/web/assets/b1c24d7/web.assets_web.min.js:4221:129)
    at visitChildren (http://localhost:8069/web/assets/b1c24d7/web.assets_web.min.js:4220:171)
    at visit (http://localhost:8069/web/assets/b1c24d7/web.assets_web.min.js:4221:129)
    at visitChildren (http://localhost:8069/web/assets/b1c24d7/web.assets_web.min.js:4220:171)
    at visit (http://localhost:8069/web/assets/b1c24d7/web.assets_web.min.js:4221:129)
    at visitChildren (http://localhost:8069/web/assets/b1c24d7/web.assets_web.min.js:4220:171)

**Comment by odoomates** [comment]
hi @Circlegent ,
Follow this steps:

* Enable debug mode
* Navigate the views menu under settings -> technical -> user interface
* search for the view containing the field "anglo_saxon_accounting" , ensure to search inside the view architecture
* delete the view from the db
* upgrade om_account_accountant module

**Comment by algarih** [comment]
SOLUTION FOR this error:

connect to odoo database using terminal and run this sql:

DELETE FROM ir_ui_view WHERE arch_db::text LIKE '%anglo_saxon_accounting%';
