### ISSUE TITLE
[16.0] Unexpected "owl" Error message when trying to display a fixed asset in Dutch Language

### ISSUE THREAD

**Issue by E4eqRL0yw0yajQJ433QL** [odoomates/odooapps#136]
I just upgraded from odoo15 CE to odoo16 CE.
Since the upgrade, I get an error when displaying a fixed asset, but only when logged in with the Dutch language.
"Uncaught Promise > An error occured in the owl lifecycle (see this Error's "cause" property)"

When I switch to the English Language (with the same user), I do not get the error.

**Steps to reproduce:**

- Logon in Dutch language
- Start, accounting (facturatie), accounting (boekhouding), assets (activa): Leads to a list of my assets
- (Double)clicking on any of those assets leads to the mentioned error
- When I switch to English language with the same user, the error does not appear and the asset is displayed as expected.

**Actions already taken in trying to resolve the issue:**

- Updated odoo to latest version: Odoo 16.0-20240405 (Community-editie)
- Updated om_account_accountant (16.0.1.0.0) and om_account_asset (16.0.1.3.0) modules to latest version
- Updated the Dutch translations
- I regenerated the asset bundles (no visible impact)

**Suspected module**
om_account_asset

**Detailed Error message**
TypeError: Cannot read properties of undefined (reading 'writeText')
    at ClientErrorDialog.onClickClipboard (http://xxx.xxx.x.x:xxxx/web/assets/2906-1e5005e/web.assets_backend.min.js:639:48)
    at Object.mainEventHandler (http://xxx.xxx.x.x:xxxx/web/assets/2905-71c4cd9/web.assets_common.min.js:1999:77)
    at HTMLButtonElement.listener (xxx.xxx.x.x:xxxx/web/assets/2905-71c4cd9/web.assets_common.min.js:1175:15)

**Comment by E4eqRL0yw0yajQJ433QL** [comment]
Did some research and it turns out this error was caused by a language (translation) problem. I was  able to fix this by updating the contents of the nl_NL Dutch language. First exported nl_BE language as PO file and then imported this file as nl_NL. After re-activating (updating) nl_NL, the error message was gone.
