### ISSUE TITLE
[12.0] Error while printing PDF

### ISSUE THREAD

**Issue by FedericoLaTorre** [odoomates/odooapps#20]
Error while printing PDF of any of the reports. It works OK with any other modules. If I configure them as HTML the report works fine.

ERROR Vignelli odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1012, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('account.common.journal.report(7,).company_id', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 835, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/aeroo_reports/report_aeroo/controllers/main.py", line 36, in report_routes
    **data)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/reporting-engine-oca/report_xlsx_helper/controllers/main.py", line 54, in report_routes
    reportname, docids, converter, **data)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/reporting-engine-oca/report_xlsx/controllers/main.py", line 59, in report_routes
    reportname, docids, converter, **data
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1616, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions_report.py", line 727, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/opt/odoo/reporting-engine/report_extended/models/ir_actions_report.py", line 204, in render_qweb_html
    self = self._extend_report_context(docids, data=data)
  File "/opt/odoo/reporting-engine/report_extended_stock/models/report.py", line 64, in _extend_report_context
    docids, data=data)
  File "/opt/odoo/reporting-engine/report_extended_sale/models/report.py", line 32, in _extend_report_context
    docids, data=data)
  File "/opt/odoo/reporting-engine/report_extended_payment_group/models/report_payment_group.py", line 48, in _extend_report_context
    docids, data=data)
  File "/opt/odoo/reporting-engine/report_extended_account/models/report_invoice.py", line 106, in _extend_report_context
    docids, data=data)
  File "/opt/odoo/reporting-engine/report_extended/models/ir_actions_report.py", line 128, in _extend_report_context
    if recs and 'company_id' in recs._fields and recs[0].company_id:
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1019, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1053, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1096, in getter
    raise exception
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2820, in read
    vals[name] = convert(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5148, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1012, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1053, in get
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1096, in getter
    raise exception
odoo.exceptions.MissingError: ('El registro no existe o ha sido eliminado.\n\n(Registros: account.common.journal.report(7,), Usuario: 10)', None)

**Comment by odoomates** [comment]
Still the issue is not reproducible for us, if you are still facing issue, please let us know.
