### ISSUE TITLE
 Installing error message

### ISSUE THREAD

**Issue by agemticcl** [odoomates/odooapps#4]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo/models.py", line 1108, in _validate_fields
    check(self)
  File "/opt/odoo12/odoo/addons/base/models/ir_ui_view.py", line 345, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/opt/odoo12/odoo/addons/base/models/ir_ui_view.py", line 784, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/opt/odoo12/odoo/addons/base/models/ir_ui_view.py", line 732, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/opt/odoo12/odoo/addons/base/models/ir_ui_view.py", line 710, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/opt/odoo12/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
    raise ValueError(message)
ValueError: El elemento '<field name="journal_ids">' no puede ser localizado en la vista padre

Contexto del error:
Vista `Trial Balance`
[view_id: 2312, xml_id: n/a, model: account.balance.report, parent_id: 561]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo12/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo12/odoo/models.py", line 3865, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo12/addons/website/models/ir_ui_view.py", line 129, in _load_records_create
    records = super(View, self)._load_records_create(values)
  File "/opt/odoo12/odoo/models.py", line 3779, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/opt/odoo12/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo12/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/models.py", line 3596, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo12/odoo/fields.py", line 1117, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo12/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/opt/odoo12/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/opt/odoo12/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo12/odoo/models.py", line 3321, in write
    self._write(store_vals)
  File "/opt/odoo12/odoo/models.py", line 3457, in _write
    self._validate_fields(vals)
  File "/opt/odoo12/odoo/models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error mientras se validaban las restricciones\n\nEl elemento \'<field name="journal_ids">\' no puede ser localizado en la vista padre\n\nContexto del error:\nVista `Trial Balance`\n[view_id: 2312, xml_id: n/a, model: account.balance.report, parent_id: 561]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo12/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo12/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo12/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/opt/odoo12/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo12/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo12/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo12/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo12/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo12/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo12/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/odoo12/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo12/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo12/odoo/tools/convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo12/odoo/tools/convert.py", line 764, in parse
    exc_info[2]
  File "/opt/odoo12/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo12/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo12/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo12/odoo/models.py", line 3865, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo12/addons/website/models/ir_ui_view.py", line 129, in _load_records_create
    records = super(View, self)._load_records_create(values)
  File "/opt/odoo12/odoo/models.py", line 3779, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/opt/odoo12/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo12/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/models.py", line 3596, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo12/odoo/fields.py", line 1117, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo12/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/opt/odoo12/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/opt/odoo12/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo12/odoo/models.py", line 3321, in write
    self._write(store_vals)
  File "/opt/odoo12/odoo/models.py", line 3457, in _write
    self._validate_fields(vals)
  File "/opt/odoo12/odoo/models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error mientras se validaban las restricciones

El elemento '<field name="journal_ids">' no puede ser localizado en la vista padre

Contexto del error:
Vista `Trial Balance`
[view_id: 2312, xml_id: n/a, model: account.balance.report, parent_id: 561]
None" while parsing /opt/odoo12/addons/accounting_pdf_reports/wizards/trial_balance.xml:4, near
<record id="account_report_balance_view" model="ir.ui.view">
        <field name="name">Trial Balance</field>
        <field name="model">account.balance.report</field>
        <field name="inherit_id" ref="account.account_common_report_view"/>
        <field name="arch" type="xml">
            <data>
            <field name="journal_ids" position="replace"/>
                <xpath expr="//field[@name='target_move']" position="after">
                    <field name="display_account" widget="radio"/>
                    <newline/>
                </xpath>
            </data>
        </field>
    </record>

**Comment by odoomates** [comment]
Hi,
We are not able to reproduce the error. If you have got any images/Videos please share for more information.
Thanks
