### ISSUE TITLE
[14.0.7.1.0] om_hr_payroll Field "hra" does not exist in model "hr.contract"

### ISSUE THREAD

**Issue by donatid** [odoomates/odooapps#44]
Hello,

I found issue when tried to upgrade existing module to the latest version 14.0.7.1.0 in my odoo 14, here the error log:

```
2021-10-14 20:59:24,715 3357682 INFO dbodoodev odoo.modules.loading: loading om_hr_payroll/views/hr_contract_views.xml 
2021-10-14 20:59:24,793 3357682 INFO dbodoodev odoo.addons.base.models.ir_ui_view: Field "hra" does not exist in model "hr.contract"

View name: hr.contract.view.form.inherit
Error context:
 view: ir.ui.view(3437,)
 xmlid: hr_contract_form_inherit
 view.model: hr.contract
 view.parent: ir.ui.view(1181,)
 file: /home/donatid/custom-addons/om_hr_payroll/views/hr_contract_views.xml
 
2021-10-14 20:59:24,805 3357682 WARNING dbodoodev odoo.modules.loading: Transient module states were reset 
2021-10-14 20:59:24,836 3357682 ERROR dbodoodev odoo.modules.registry: Failed to load registry 
2021-10-14 20:59:24,837 3357682 ERROR dbodoodev odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/home/donatid/odoo/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/donatid/odoo/odoo/tools/convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/donatid/odoo/odoo/models.py", line 4213, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/donatid/odoo/odoo/models.py", line 4142, in _load_records_create
    return self.create(values)
  File "<decorator-gen-43>", line 2, in create
  File "/home/donatid/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/home/donatid/odoo/odoo/addons/base/models/ir_ui_view.py", line 482, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-65>", line 2, in create
  File "/home/donatid/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/home/donatid/odoo/odoo/addons/base/models/ir_fields.py", line 534, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/home/donatid/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/home/donatid/odoo/odoo/models.py", line 3903, in create
    fields[0].determine_inverse(batch_recs)
  File "/home/donatid/odoo/odoo/fields.py", line 1185, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/donatid/odoo/odoo/addons/base/models/ir_ui_view.py", line 300, in _inverse_arch
    view.write(data)
  File "/home/donatid/odoo/addons/website/models/theme_models.py", line 267, in write
    res = super(IrUiView, other_views).write(vals)
  File "/home/donatid/odoo/addons/website/models/ir_ui_view.py", line 68, in write
    return super(View, self).write(vals)
  File "/home/donatid/odoo/odoo/addons/base/models/ir_ui_view.py", line 500, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/home/donatid/odoo/odoo/models.py", line 3687, in write
    real_recs._validate_fields(vals, inverse_fields)
  File "/home/donatid/odoo/odoo/models.py", line 1266, in _validate_fields
    check(self)
  File "/home/donatid/odoo/odoo/addons/base/models/ir_ui_view.py", line 408, in _check_xml
    raise ValidationError(_(
  File "/home/donatid/odoo/odoo/addons/base/models/ir_ui_view.py", line 391, in _check_xml
    view.postprocess_and_fields(view_doc, validate=True)
  File "/home/donatid/odoo/odoo/addons/base/models/ir_ui_view.py", line 851, in postprocess_and_fields
    arch, name_manager = self._postprocess_view(node, model, validate=validate)
  File "/home/donatid/odoo/odoo/addons/base/models/ir_ui_view.py", line 863, in _postprocess_view
    self.postprocess(node, [], editable, name_manager)
  File "/home/donatid/odoo/odoo/addons/base/models/ir_ui_view.py", line 963, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  File "/home/donatid/odoo/odoo/addons/base/models/ir_ui_view.py", line 963, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  File "/home/donatid/odoo/odoo/addons/base/models/ir_ui_view.py", line 963, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  [Previous line repeated 4 more times]
  File "/home/donatid/odoo/odoo/addons/base/models/ir_ui_view.py", line 954, in postprocess
    validator(node, name_manager, node_info)
  File "/home/donatid/odoo/odoo/addons/base/models/ir_ui_view.py", line 1090, in _validate_tag_field
    self.handle_view_error(msg)
  File "/home/donatid/odoo/odoo/addons/base/models/ir_ui_view.py", line 673, in handle_view_error
    raise ValueError(formatted_message).with_traceback(from_traceback) from from_exception
odoo.exceptions.ValidationError: Error while validating view:

Field "hra" does not exist in model "hr.contract"

View name: hr.contract.view.form.inherit
Error context:
 view: ir.ui.view(3437,)
 xmlid: hr_contract_form_inherit
 view.model: hr.contract
 view.parent: ir.ui.view(1181,)
 file: /home/donatid/custom-addons/om_hr_payroll/views/hr_contract_views.xml


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/donatid/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/donatid/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/home/donatid/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/donatid/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/donatid/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/donatid/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/home/donatid/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/home/donatid/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/donatid/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/donatid/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/donatid/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-72>", line 2, in button_immediate_install
  File "/home/donatid/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/donatid/odoo/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/donatid/odoo/odoo/addons/base/models/ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/donatid/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/donatid/odoo/odoo/modules/loading.py", line 459, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/donatid/odoo/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/donatid/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/donatid/odoo/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/donatid/odoo/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/donatid/odoo/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/donatid/odoo/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/home/donatid/odoo/odoo/tools/convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/donatid/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/donatid/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /home/donatid/custom-addons/om_hr_payroll/views/hr_contract_views.xml:16, near
<record id="hr_contract_form_inherit" model="ir.ui.view">
        <field name="name">hr.contract.view.form.inherit</field>
        <field name="model">hr.contract</field>
        <field name="inherit_id" ref="hr_contract.hr_contract_view_form"/>
        <field name="arch" type="xml">
            <data><xpath expr="//field[@name='job_id']" position="after">
                <field name="struct_id" required="1"/>
            </xpath>
            <xpath expr="//field[@name='job_id']" position="before">
                <field name="company_id" groups="base.group_multi_company"/>
                <field name="currency_id" invisible="1"/>
            </xpath>
            <xpath expr="//field[@name='resource_calendar_id']" position="after">
                <field name="schedule_pay"/>
            </xpath>

            <xpath expr="//page[@name='information']" position="after">
                <page name="other" position="move"/>
            </xpath>

            <xpath expr="//group[@name='salary_and_advantages']" position="after">
                <group string="Monthly Advantages in Cash" name="allowances">
                    <label for="hra"/>
                    <div class="o_row">
                        <field name="hra" nolabel="1"/>
                        <span>/ month</span>
                    </div>
                    <label for="da"/>
                    <div class="o_row">
                        <field name="da" nolabel="1"/>
                        <span>/ month</span>
                    </div>
                    <label for="travel_allowance"/>
                    <div class="o_row">

                        <field name="travel_allowance" nolabel="1"/>
                        <span>/ month</span>
                    </div>
                    <label for="meal_allowance"/>
                    <div class="o_row">

                        <field name="meal_allowance" nolabel="1"/>
                        <span>/ month</span>
                    </div>
                    <label for="medical_allowance"/>
                    <div class="o_row">

                        <field name="medical_allowance" nolabel="1"/>
                        <span>/ month</span>
                    </div>
                    <label for="other_allowance"/>
                    <div class="o_row">

                        <field name="other_allowance" nolabel="1"/>
                        <span>/ month</span>
                    </div>
                </group>
            </xpath>
        </data></field>
    </record>
```

If you have any questions please let me know.

Thank you for your help and great works.

Br,
David

**Comment by odoomates** [comment]
Hi,
Did you restarted the service after adding the latest code ?

**Comment by salytwo** [comment]
I am facing same error here, how to reach the fields hra,da travel_Allowance...etc
