### ISSUE TITLE
[14.0] om_account_asset: TypeError when Asset Type depreciation dates on Based on Last Day of Purchase Period

### ISSUE THREAD

**Issue by kwoychesko** [odoomates/odooapps#51]
If the Asset Type of the current asset has a "Depreciation Dates" setting of "Based on Last Day of Purchase Period", the compute_depreciation_board method uses the Settings fiscalyear_last_month and fiscalyear_last_day, but the method treats the data as a string instead of an int and produces the error below. Converting the str to int using int() fixes the issue.

To reproduce the error:
1. Create an Asset Type with "Depreciation Dates" as "Based on Last Day of Purchase Period".
2. Create a new asset and set a value.
3. Click the Compute Depreciation button. The error will occur.

`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/Users/kenwoychesko/code-sources/odoo-related/14.0/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/Users/kenwoychesko/code-sources/odoo-related/14.0/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/Users/kenwoychesko/code-sources/odoo-related/14.0/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/kenwoychesko/code-sources/odoo-related/14.0/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/kenwoychesko/code-sources/odoo-related/14.0/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/kenwoychesko/code-sources/odoo-related/14.0/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/Users/kenwoychesko/code-sources/odoo-related/14.0/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/Users/kenwoychesko/code-sources/odoo-related/14.0/odoo/addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/Users/kenwoychesko/code-sources/odoo-related/14.0/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/kenwoychesko/code-sources/odoo-related/14.0/odoo/odoo/api.py", line 397, in call_kw
    result = _call_kw_model_create(method, model, args, kwargs)
  File "/Users/kenwoychesko/code-sources/odoo-related/14.0/odoo/odoo/api.py", line 377, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-196>", line 2, in create
  File "/Users/kenwoychesko/code-sources/odoo-related/14.0/odoo/odoo/api.py", line 326, in _model_create_single
    return create(self, arg)
  File "/Users/kenwoychesko/code-sources/odoo-related/14.0/BPMI/odooapps/om_account_asset/models/account_asset.py", line 493, in create
    asset.sudo().compute_depreciation_board()
  File "/Users/kenwoychesko/code-sources/odoo-related/14.0/BPMI/odooapps/om_account_asset/models/account_asset.py", line 283, in compute_depreciation_board
    depreciation_date = depreciation_date + relativedelta(month=self.company_id.fiscalyear_last_month)
  File "/Users/kenwoychesko/code-development/bpmi-addons/venv/lib/python3.8/site-packages/dateutil/relativedelta.py", line 396, in __radd__
    return self.__add__(other)
  File "/Users/kenwoychesko/code-development/bpmi-addons/venv/lib/python3.8/site-packages/dateutil/relativedelta.py", line 368, in __add__
    day = min(calendar.monthrange(year, month)[1],
  File "/Users/kenwoychesko/.pyenv/versions/3.8.11/lib/python3.8/calendar.py", line 123, in monthrange
    if not 1 <= month <= 12:
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kenwoychesko/code-sources/odoo-related/14.0/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/kenwoychesko/code-sources/odoo-related/14.0/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: '<=' not supported between instances of 'int' and 'str'`

**Comment by odoomates** [comment]
Fixed with PR: https://github.com/odoomates/odooapps/commit/2b9e38b31428ad6c76c4fa206883e9712a8d9f84
